app:client:
  - "### Which app is this (bug
    report|feature request) for\\?\\n\\nclient\\n"

app:server:
  - "### Which app is this (bug
    report|feature request) for\\?\\n\\nserver\\n"

app:website:
  - "### Which app is this (bug
    report|feature request) for\\?\\n\\nwebsite\\n"
