packages:
  - apps/*

catalogs:
  build:
    tsup: ^8.5.1
    turbo: ^2.8.9
    typescript: ^5.9.3
  ci:
    '@commitlint/cli': ^20.3.1
    '@commitlint/config-conventional': ^20.4.1
    '@favware/cliff-jumper': ^6.0.0
    '@nanoforge-dev/actions': ^1.1.0
    husky: ^9.1.7
    lint-staged: ^16.2.7
  core:
    '@types/bun': ^1.3.9
    '@types/node': ^25.3.0
    bun: ^1.3.9
  lint:
    '@nanoforge-dev/utils-eslint-config': ^1.0.2
    '@nanoforge-dev/utils-prettier-config': ^1.0.1
    '@trivago/prettier-plugin-sort-imports': ^6.0.2
    eslint: ^9.39.2
    prettier: ^3.8.1
  schematics:
    '@angular-devkit/core': ^21.1.1
    '@angular-devkit/schematics': ^21.1.1

onlyBuiltDependencies:
  - bun
